-- Copia y pega este código en el Editor SQL de tu panel de Supabase para crear las tablas necesarias.

-- 1. Crear tabla de productos
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text,
  description text,
  price decimal(10,2) not null,
  stock integer default 0,
  image_url text,
  category text default 'patinete',
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Habilitar seguridad (RLS)
alter table public.products enable row level security;

-- 3. Crear políticas de acceso
-- Cualquiera puede ver productos (lectura pública)
create policy "Productos son públicos"
  on public.products for select
  using (true);

-- Solo usuarios autenticados pueden crear/editar/borrar (Admin)
create policy "Admin puede gestionar productos"
  on public.products for all
  using (auth.role() = 'authenticated');

-- 4. (Opcional) Crear bucket de almacenamiento para imágenes
-- Ve a Storage -> Create new bucket -> "products" -> Public: Yes
